### PR TITLE
Updates to include stipulations on workarounds

### PR DESCRIPTION
**Pull request by ProbablePrime**

### CODE REVIEW

**Review by BlueCyro — COMMENTED** [review]
`Therefore, until the workaround has been discussed and deemed suitable with the Neos team, please do not talk to other users about the workaround.`

I feel like this still would be inconvenient in the absence of an expedient response from the team, even if they know the fix is suitable by the team's standards. Not saying that waiting for a response from the team is a *bad* idea necessarily, but allowing for a bit of wiggle room when a fix is fairly obvious so people can whisper to their friends and help them would be good IMO. I'm imagining someone doing an antsy dance wanting to tell their friend of this *really* important, but simple fix - yet can't because they're waiting on the team to decide what's best.

**Comment by ProbablePrime** [comment]
> even if they know the fix is suitable by the team's standards
That's a problem, because many "fixes" aren't actual fixes, I have people coming up to me with all sorts of really unsuitable fixes. We can't "guess" in these cases and I don't want to encourage the community to do so either.

> expedient response from the team
I'll ensure there's a fast response.

**Comment by RileyGuy** [comment]
> 

I don't wanna encourage the community to make bad choices either, but can you really guarantee a 'fast' response? What would you consider 'fast', and do you think that will match what most people consider 'fast'?

**Comment by RileyGuy** [comment]
> 

Upon further reflection, I realize I may be a little unreasonable here. It's probably fine, then.

**Comment by ProbablePrime** [comment]
> > 
> 
> I don't wanna encourage the community to make bad choices either, but can you really guarantee a 'fast' response? What would you consider 'fast', and do you think that will match what most people consider 'fast'?

Within 48 hours is our usual response time. Honestly though I usually see security tickets within a couple of hours. I think 48 hours is plenty.

**Comment by RileyGuy** [comment]
Fair enough

**Comment by bontebok** [comment]
```6. Once an issue has been resolved you may discuss the issue publicly if you would like.```

My concern with this is that the time period is open ended, an issue which may impact the community as a whole may be in the best interest of the community for disclosure after a reasonable amount of time has elapsed for the Devs to correct the issue. Someone should not be in fear of retaliation for providing a reasonable amount of time to correct/mitigate and then bringing the issue public.

I would rather a statement that the Devs will work with the reporter to coordinate a reasonable disclosure time which would allow devs time to patch/remediate the vulnerability before it becomes public knowledge and if that time window is passed, the reporter should not fear for retaliation if they decide to publicize the vulnerability.

**Comment by ProbablePrime** [comment]
> `6. Once an issue has been resolved you may discuss the issue publicly if you would like.`
> 
> My concern with this is that the time period is open ended, an issue which may impact the community as a whole may be in the best interest of the community for disclosure after a reasonable amount of time has elapsed for the Devs to correct the issue. Someone should not be in fear of retaliation for providing a reasonable amount of time to correct/mitigate and then bringing the issue public.
> 
> I would rather a statement that the Devs will work with the reporter to coordinate a reasonable disclosure time which would allow devs time to patch/remediate the vulnerability before it becomes public knowledge and if that time window is passed, the reporter should not fear for retaliation if they decide to publicize the vulnerability.

That statement, unfortunately, isn't part of these changes. It was just moved down. 

In regards to it though, we do need a timeline here, we just don't have a suitable one given the current circumstances. So its left at as is for now. This isn't meant to hide or disguise things from our community, its meant to protect them until we can resolve items. 

If you're concerned about a particular outstanding issue please open a ticket, or reply to an existing report. Thank you.

**Comment by bontebok** [comment]
> > `6. Once an issue has been resolved you may discuss the issue publicly if you would like.`
> > My concern with this is that the time period is open ended, an issue which may impact the community as a whole may be in the best interest of the community for disclosure after a reasonable amount of time has elapsed for the Devs to correct the issue. Someone should not be in fear of retaliation for providing a reasonable amount of time to correct/mitigate and then bringing the issue public.
> > I would rather a statement that the Devs will work with the reporter to coordinate a reasonable disclosure time which would allow devs time to patch/remediate the vulnerability before it becomes public knowledge and if that time window is passed, the reporter should not fear for retaliation if they decide to publicize the vulnerability.
> 
> That statement, unfortunately, isn't part of these changes. It was just moved down.

I was reviewing the Diff and it looked like it was added, my apologies. I had also not reviewed these in much detail until now. Let me know if I should place these comments elsewhere so they get tracked for future changes.

> In regards to it though, we do need a timeline here, we just don't have a suitable one given the current circumstances. So its left at as is for now. This isn't meant to hide or disguise things from our community, its meant to protect them until we can resolve items.

Agreed, but the timeline or timeframe doesn't have to be public, many companies work out a disclosure time privately with the reporter as they can request a reasonable timeframe. The report is given in good faith, otherwise the party would just have disclosed it publicly anyway, so it's amicable for both parties to agree on that timeframe. There's also a bounty so the incentive is already there for the reporter to stick to that timeframe.

I agree with your statement about the protection of the community, but public disclosure ahead of a patch may also protect the community especially if it can lead to separate action (like changing a setting, adding firewall rules, applying a workaround, discontinuing use, looking for IOC's, etc) that may provide some level of protection, detection, recovery etc.
 
> If you're concerned about a particular outstanding issue please open a ticket, or reply to an existing report. Thank you.

Are you asking me? I don't have any outstanding security concerns at this time :)

Thanks

**Pull request merged**
